<?php
/**
 * Notes: api基类-控制器，继承 yii\rest\ActiveController
 * User: zhangjinyu
 * Email: 363626256@qq.com
 * Time: 2020/12/5 11:24
 */
namespace api\controllers;

use phpDocumentor\Reflection\Types\Object_;
use yii\rest\ActiveController;

class BaseController extends ActiveController
{
    public $modelClass = '';

    /**
     * @Notes: 资源控制器中的所有路径方法
     * @return array
     * @Author: zhangjinyu
     * @Email: 363626256@qq.com
     * @Time: 2020/12/5 11:25
     */
    public function actions()
    {
        $actions = parent::actions(); // TODO: Change the autogenerated stub
        // 销毁对应路由，由控制器进行自定义返回格式
        unset(
            $actions['index'],
            $actions['view'],
            $actions['options'],
            $actions['create'],
            $actions['delete'],
            $actions['update']
        );

        return $actions;
    }

    /**
     * @Notes: 成功时返回数据
     * @param $data
     * @param $status
     * @param $message
     * @return array
     * @Author: zhangjinyu
     * @Email: 363626256@qq.com
     * @Time: 2020/11/29 19:33
     */
    public function success($data = [], $status = 200, $message = 'OK')
    {
        return $this->jsonFormat($data, $status, $message);
    }


    /**
     * @Notes: 失败时返回数据
     * @param array $data
     * @param $status
     * @param $message
     * @return array
     * @Author: zhangjinyu
     * @Email: 363626256@qq.com
     * @Time: 2020/11/29 19:33
     */
    public function error($data = [], $status = 404, $message = 'ERROR')
    {

        return $this->jsonFormat($data, $status, $message);
    }

    /**
     * @Notes: 格式化返回数据
     * @param $data array 返回数据
     * @param $status integer 返回的状态码
     * @param $message string 返回的信息
     * @return array
     * @Author: zhangjinyu
     * @Email: 363626256@qq.com
     * @Time: 2020/11/29 19:32
     */
    public function jsonFormat($data, $status, $message)
    {
        \Yii::$app->response->format = 'json';
        return [
            'data' => (Object)$data,
            'status' => (Int)$status,
            'message' => (String)$message
        ];
    }
}